name: Bug Report
description: Report a bug to the developer.
title: "[Bug] <title>"
labels: [New, Bug]
body:
- type: textarea
  attributes:
    label: The Problem
    description: Describe what the problem is and its behaviour.
    placeholder: "Eg. Permissions don't work when they say they do."
  validations:
    required: true
- type: dropdown
  attributes:
    label: Build Information
    options:
      - 1.7.0 (Forge 1.19.4)
      - 1.6.0 (Forge 1.19.2)
      - 1.5.0 (Forge 1.19.4)
      - 1.4.0 (Forge 1.19.2)
      - 1.3.0 (Forge 1.19.2)
      - 1.2.0 (Forge 1.19.2)
      - 1.1.0 (Forge 1.18.2)
      - 1.0.0 (Forge 1.17.1)
  validations:
    required: true
- type: textarea
  attributes:
    label: Attachments
    description: Attach files such as screenshots, crash reports, or game logs so we can narrow down the issue.
    placeholder: Screenshots are optional, but the other two much be attached. Crash reports are only required when there is a crash.
  validations:
    required: false
